version: '3'

services:
  summarizer:
    build: .
    ports:
      - 8889:8889
    volumes:
      - /data:/code/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
