version: '3'

services:
  summarizer:
    build: .
    ports:
      - 7860:7860
    volumes:
      - /data:code/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
